### ISSUE TITLE
Build results in: npm ERR! Tracker "idealTree" already exists (also, npm notice to upgrade when latest version is installed)

### ISSUE THREAD

**Issue by prototowb** [docker/for-linux#1207]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
build the image

### Actual behavior
exit the build-process with an error:

-=-

Step 4/6 : RUN npm install
 ---> Running in d2f2c6be7087
npm notice 
npm notice New patch version of npm available! 7.5.1 -> 7.5.4
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.5.4>
npm notice Run `npm install -g npm@7.5.4` to update!
npm notice 
npm ERR! Tracker "idealTree" already exists

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-19T13_36_14_302Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1

-=-

Also, I have npm version 7.5.4 installed. I don't know why this notice shows up.

### Steps to reproduce the behavior
not sure

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:47 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:32:03 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 30
  Running: 3
  Paused: 0
  Stopped: 27
 Images: 63
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1028-raspi
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.628GiB
 Name: bulldozer
 ID: SD6J:EXLR:QD6I:QIW7:LRGY:T5WJ:XGNZ:DCBX:VSZG:CLBI:AAMU:V4AM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by naik899** [comment]
Any update here?

**Comment by thaJeztah** [comment]
I don't think this is a bug in docker itself, but I see this question being asked on stackoverflow, which has some answers; https://stackoverflow.com/questions/57534295/npm-err-tracker-idealtree-already-exists-while-creating-the-docker-image-for
