### ISSUE TITLE
17.06.0 RC5 tracker

### ISSUE THREAD

**Issue by andrewhsu** [docker/for-linux#37]
**STATUS: finished merging list of desired cherry-picks**

- [x] docker/swarmkit#2268 `p0` - docker/docker-ce#84 @aaronlehmann scheduler: Clean up addOrUpdateNode
- [x] moby/moby#33712 `p1` - docker/docker-ce#84 @cyli Redact swarm spec CA signing cert for usability reasons
- [x] docker/swarmkit#2224 `p1` - docker/docker-ce#84 @cyli [ca] GetRemoteSignedCertificate downloads cert in Issuance or Rotate state
- [x] docker/libnetwork#1808 `p1` - docker/docker-ce#85 @fcrisciani Service discovery race on serviceBindings delete. Bug on IP reuse
- [x] docker/cli#182 `p1` - docker/docker-ce#87 @vdemeester @friism Do not call the config endpoint if API is lower than 1.30 (related: docker/cli#180)
- [x] docker/swarmkit#2263 `p2` - docker/docker-ce#84 @cyli [controlapi] Redact the cluster spec CA signing certificate when getting the cluster info

**Backlog**

- moby/moby#33735 `p2` - docker/docker-ce#86 @tonistiigi builder: fix copy —from conflict with force pull
- moby/moby#33402 `p1` - Swarm Mode assigns similar IP addresses for different services
- docker/cli#72 `p1` - docker/docker-ce#77 @thaJeztah fixes nasty ux issue/regression (see https://github.com/moby/moby/pull/32800 and https://github.com/moby/moby/issues/32556)
- docker/cli#155 `p1` - only the bump of `docker-credential-helpers`
- moby/moby#33422 per https://github.com/docker/for-linux/issues/2#issuecomment-304559327 (simple cherry-pick PR) looks like this is already in
- ~moby/moby#33500 @mlaventure: needed before GA, fixes regression within builder (see moby/moby#33493) https://github.com/docker/for-linux/issues/2#issuecomment-305902054 (simple cherry-pick PR) looks like this is already in~
- docker/docker-credential-helpers#62 per https://github.com/docker/for-linux/issues/2#issuecomment-304619127

**Comment by seemethere** [comment]
If we are having an RC5 we should cherry pick the docker-ce-packaging things as well:

* https://github.com/docker/docker-ce-packaging/pull/20
* https://github.com/docker/docker-ce-packaging/pull/22
* https://github.com/docker/docker-ce-packaging/pull/21

**Comment by tonistiigi** [comment]
Another `rc5` candidate (cc @thaJeztah): https://github.com/moby/moby/pull/33735
Regression only in `v17.06`

**Comment by andrewhsu** [comment]
@tonistiigi sorry, #86 will have to miss the RC5 boat because test job is still running and we gotta keep rolling. It'll be candidate for the .1 release.

**Comment by andrewhsu** [comment]
Closing this issue because docker-ce 17.06.0 rc5 is out the door. Backlog copied here:

- moby/moby#33735 `p2` - docker/docker-ce#86 @tonistiigi builder: fix copy —from conflict with force pull
- moby/moby#33402 `p1` - Swarm Mode assigns similar IP addresses for different services
- docker/cli#72 `p1` - docker/docker-ce#77 @thaJeztah fixes nasty ux issue/regression (see https://github.com/moby/moby/pull/32800 and https://github.com/moby/moby/issues/32556)
- ~docker/cli#155 `p1` - only the bump of `docker-credential-helpers`~ taken care of in docker for mac
- ~moby/moby#33422 per https://github.com/docker/for-linux/issues/2#issuecomment-304559327 (simple cherry-pick PR)~ this is already in
- ~moby/moby#33500 @mlaventure: needed before GA, fixes regression within builder (see moby/moby#33493) https://github.com/docker/for-linux/issues/2#issuecomment-305902054 (simple cherry-pick PR)~ this is already in
- ~docker/docker-credential-helpers#62 per https://github.com/docker/for-linux/issues/2#issuecomment-304619127~ taken care of in docker for mac
