### ISSUE TITLE
17.06.0 RC3 tracker

### ISSUE THREAD

**Issue by andrewhsu** [docker/for-linux#8]
**STATUS: completed merge list for RC3**

- [x] containerd/containerd#930 `p1` - docker/docker-ce#14 @mlaventure update containerd
- [x] containerd/containerd#706 `p3` - docker/docker-ce#14 @mlaventure update containerd
- [x] containerd/containerd#855 `p1` - docker/docker-ce#14 @mlaventure update containerd
- [x] moby/moby#33577 `p0` - docker/docker-ce#54 fix TTY issues due to RunC change, be sure to reference 33577 (PR should git revert fff42c853aedd3e15c731217058642d9859e7d3f from https://github.com/docker/docker-ce/pull/25)
- [x] moby/moby#33578 `p0` - docker/docker-ce#45 Regression introduced in 17.06 (simple cherry-pick PR)
- [x] docker/cli#166 `p0` - docker/docker-ce#54 @thajeztah fixes the CLI issues of OPOST, be sure to reference 166 (git revert 972de9a65734e146fa4d3b5672b5c7073dd39b1f from docker/docker-ce#25)
- [x] docker/cli#121 `p1` - docker/docker-ce#44 @aaronlehmann not taking it will cause regression (simple cherry-pick PR) needs special attention for tests updated in moby/moby#33386
- [x] docker/cli#150 `p1` - docker/docker-ce#46 @vdemeester breaks stack deploy on older daemon (simple cherry-pick PR of docker/cli#162 )
- [x] docker/swarmkit#2215 `p1` - @cyli docker/docker-ce#43 revendor swarmkit
- [x] docker/swarmkit#2218 `p1` - @cyli docker/docker-ce#43 revendor swarmkit
- [x] docker/swarmkit#2233 `p1` - docker/docker-ce#43 @cyli @aaronlehmann fixes a crash bug, revendor swarmkit
- [x] moby/moby#33249 `p1` - docker/docker-ce#47 @thaJeztah fixes healthchecks failing in some situations (simple cherry-pick PR)
- [x] moby/moby#33330 `p1` - docker/docker-ce#48 alleviate possible issues for UCP (simple cherry-pick PR)
- [x] moby/moby#33464 `p1` - docker/docker-ce#49 @cyli (simple cherry-pick PR)
- [x] moby/moby#33524 `p1` - docker/docker-ce#50 fix builder cache when using ONBUILD (simple cherry-pick PR)
- [x] docker/libnetwork#1786 `p1` - need to cherry-pick into https://github.com/docker/libnetwork/tree/bump_17.06.0 and then open PR to bump vendor in components/engine/vendor.conf
- [x] docker/libnetwork#1787 `p1` - same as 1786
- [x] docker/libnetwork#1789 `p1` - same as 1786
- [x] moby/moby#33555 `p1` - docker/docker-ce#55 @mavenugo vendoring libnetwork and netlink into engine related to 1786, 1787, 1789
- [x] moby/moby#33307 `p2` - docker/docker-ce#51 @mavenugo fix flakey DockerSwarmSuite.TestSwarmClusterEventsSecret (simple cherry-pick PR)
- [x] moby/moby#33335 `p2` - docker/docker-ce#52 @cpuguy83 to confirm (simple cherry-pick PR)
- [x] moby/moby#33419 `p2` - docker/docker-ce#53 @mlaventure if we don't have customers using non-official packages (simple cherry-pick PR)
- [x] docker/cli#173 `p1` - docker/docker-ce#56 @andrewhsu use golang 1.8.3 instead of golang 1.8.1 for building docker.exe
- [x] docker/cli#79 `p1` - docker/docker-ce#32 (vendor) @nishanttotla 
- [x] docker/cli#79 `p1` - docker/docker-ce#13 (cherry-pick) @nishanttotla 
- [x] moby/moby#33413 `p2` - docker/docker-ce#57 @thaJeztah discussing with @cpuguy83 https://github.com/docker/for-linux/issues/2#issuecomment-305185213 (simple cherry-pick PR)
- [x] moby/moby#33363 `p2` - docker/docker-ce#58 @thaJeztah may not be critical per discussion https://github.com/docker/for-linux/issues/2#issuecomment-305273265 (simple cherry-pick PR)
- [x] moby/moby#33473 `p3` - docker/docker-ce#59 @thaJeztah docs updated for email flag deprecation (simple cherry-pick PR)
- [x] docker/cli#144 `p2` - docker/docker-ce#60 @vdemeester: https://github.com/docker/for-linux/issues/2#issuecomment-305562265 (simple cherry-pick PR)
- [x] moby/moby#33583 `p2` - docker/docker-ce#61 @cpuguy83 (https://github.com/moby/moby/issues/33569#issuecomment-306810688) (simple cherry-pick PR)
- [x] moby/moby#33598 `p1` - docker/docker-ce#62 @aaronlehmann sending SIGUSR1 to the docker daemon can crash it (simple cherry-pick PR)
- [x] moby/moby#33606 `p3` - docker/docker-ce#63 @thaJeztah add 17.05.0-ce to changelog (simple cherry-pick PR)
- [x] moby/moby#33634 `p1` - docker/docker-ce#66 @mavenugo vendor libnetwork
- [x] docker/cli#143 `p2` - docker/docker-ce#64 @thaJeztah removes the email flag from docker login, scheduled deprecation in 17.06 (simple cherry-pick PR, also include moby/moby/pull/33636)
- [x] moby/moby#33609 `p1` - docker/docker-ce#65 missing backport to master, already in 1.13 and 17.03, fixes possible panic (but please confirm @mavenugo ) (simple cherry-pick PR)
- [x] docker/swarmkit#2234 `p1` - docker/docker-ce#69 @cyli 
- [x] docker/swarmkit#2237 `p1` - docker/docker-ce#69 @aaronlehmann allocator: Avoid assigning duplicate IPs during initialization
- [x] docker/swarmkit#2238 `p1` - docker/docker-ce#69 @cyli 
- [x] moby/moby#33629 `p1` - docker/docker-ce#71 @thaJeztah disable v1 registries by default
- [x] moby/moby#33577 `p0` - docker/docker-ce#70 - @tiborvass

**Comment by cyli** [comment]
>  moby/moby#33464 p1 - @cyli to confirm

Yes, p1

**Comment by cyli** [comment]
Also, the following two swarmkit PRS have been cherry-picked into the swarmkit 17.06 branch already and should also be in rc3:

- https://github.com/docker/swarmkit/pull/2212 `p1`
- https://github.com/docker/swarmkit/pull/2210 `p1`

**Comment by mlaventure** [comment]
would add https://github.com/moby/moby/pull/33456 as a p1

**Comment by thaJeztah** [comment]
I think there were a couple of PRs left as comment that were not yet added to the checkbox list

**Comment by ybalt** [comment]
Hi guys, can you please take a look at issue #32195 mentioned by vovimayhem, as it really a showstopper for many people

**Comment by skinofstars** [comment]
Please consider including https://github.com/docker/cli/issues/150 as it's breaking deployment on current release of Mac (17.06) and Cloud (17.05)

**Comment by kinghuang** [comment]
For docker/cli#150, @vdemeester has a PR at docker/cli#162.

**Comment by thaJeztah** [comment]
Adding https://github.com/moby/moby/pull/33577, which reverts a breaking change in RunC

**Comment by thaJeztah** [comment]
Ok, I just went through all the comments on the old issue, checked if they were included in the old issue checklist, then checked if they were included in _this_ issue checklist, and looks like the following suggested PR's / issues didn't make it from the old to the new issue.

(I think we should stick to using a single issue, because this is quite time-consuming, and easy to lose track)

- [ ] https://github.com/moby/moby/pull/33422 (https://github.com/docker/for-linux/issues/2#issuecomment-304559327)
- [ ] https://github.com/docker/docker-credential-helpers/pull/62 (https://github.com/docker/for-linux/issues/2#issuecomment-304619127)
- [ ] https://github.com/moby/moby/pull/33413 @thaJeztah: "Discussing with @cpuguy83 - possibly moby/moby#33413 is good to include" https://github.com/docker/for-linux/issues/2#issuecomment-305185213
- [ ] https://github.com/moby/moby/pull/33363 @thaJeztah: "Possibly moby/moby#33363, but may not be critical (per the discussion on that issue)" https://github.com/docker/for-linux/issues/2#issuecomment-305273265
- [ ] https://github.com/docker/cli/pull/72 @thaJeztah: "it fixes a nasty ux issue/regression (see https://github.com/moby/moby/pull/32800, and https://github.com/moby/moby/issues/32556)
- [ ] https://github.com/docker/cli/pull/143 @thaJeztah: "removes  the `-e` / `--email` flag from `docker login`, which was scheduled to be removed in 17.06."
- [ ] https://github.com/moby/moby/pull/33473 @thaJeztah: docs updated for the above
- [ ] https://github.com/moby/moby/pull/33472 @thaJeztah: something to consider (if CI is fixed)
- [ ] https://github.com/docker/swarmkit/pull/2210 @cyli: fix for a bug with external CAs in swarmkit https://github.com/docker/for-linux/issues/2#issuecomment-305557758
- [ ] https://github.com/docker/cli/pull/144 @vdemeester: https://github.com/docker/for-linux/issues/2#issuecomment-305562265
- [ ] https://github.com/moby/moby/pull/33500 @mlaventure: is needed before GA, it fixes a regression within the builder (see https://github.com/moby/moby/issues/33493) https://github.com/docker/for-linux/issues/2#issuecomment-305902054.
- [ ] https://github.com/docker/cli/issues/162 `p1` @vdemeester: should go in too (labelled it P1 because it really looks like a regression or at least it should not error out) https://github.com/docker/for-linux/issues/2#issuecomment-306001476

**Comment by thaJeztah** [comment]
This one should also be added /cc @madhu https://github.com/moby/moby/pull/33555 (or a separate PR against docker-ce)

**Comment by andrewhsu** [comment]
@thaJeztah i've added your list to the `backlog` section so it can get a priority and then move up into the cherry-pick pr list as appropriate

**Comment by cyli** [comment]
@andrewhsu Can https://github.com/docker/swarmkit/pull/2210 be moved off the backlog because it was merged into the 17.06 branch already?  (https://github.com/docker/docker-ce/commit/0efdcc403ec27e3e6835d68aae55bc3f4ac4a805)

**Comment by aaronlehmann** [comment]
Sending SIGUSR1 to the docker daemon can crash it. This issue has been showing up in the field. https://github.com/moby/moby/pull/33598 should fix it.

**Comment by cyli** [comment]
(have opened https://github.com/docker/docker-ce/pull/43 for the swarmkit cherry-picks)

**Comment by nishanttotla** [comment]
I've opened https://github.com/docker/docker-ce/pull/44 to include cherry-picks related to digest pinning for `docker stack deploy` (https://github.com/docker/cli/pull/121)

**Comment by andrewhsu** [comment]
I've updated the list at the top from all comments in this issue thus far. Identified some of the trickier PRs that will need to be created for libnetwork vendoring (with help from @tiborvass ). Need help on prioritization @mavenugo and there seems to be some unfinished issues still open.

**Comment by thaJeztah** [comment]
https://github.com/docker/cli/pull/143 should be included; it's a deprecation that was postponed already a few times

**Comment by thaJeztah** [comment]
@mavenugo tentatively adding https://github.com/moby/moby/pull/33609, which was not backported to master, but is part of 1.13 / 17.03, and fixes a possible panic (but please verify)

**Comment by mavenugo** [comment]
@thaJeztah Good catch and agreed. I will spend some time this morning to review the pending PRs in the list.

**Comment by aaronlehmann** [comment]
Let's also include https://github.com/docker/swarmkit/pull/2233. This fixes a crash bug.

**Comment by aaronlehmann** [comment]
Nominating https://github.com/docker/swarmkit/pull/2237, which is related to a defect in the allocator that causes it to assign duplicate IPs.

**Comment by thaJeztah** [comment]
@mavenugo @andrewhsu @aaronlehmann we need https://github.com/moby/moby/pull/33629 as well; the deprecation plan was to disable v1 registries by default in 17.06, so that users have enough time to migrate their legacy registries in time for support them being removed in v17.12

**Comment by mavenugo** [comment]
@aaronlehmann https://github.com/docker/swarmkit/pull/2233 is cherry-picked. Once https://github.com/docker/swarmkit/pull/2237 is in swarmkit master, can you pls chery-pick into swarmkit 1706 bump branch and open a PR in docker-ce ?

I added this PR to the tracking list above.

**Comment by vdemeester** [comment]
@mavenugo https://github.com/docker/cli/issues/180 should be included too (fixing in https://github.com/docker/cli/pull/182)

**Comment by cyli** [comment]
I'd also like to include:  https://github.com/docker/swarmkit/pull/2234 and https://github.com/docker/swarmkit/pull/2238, since they help resolve edge cases when there's a demotion during CA rotation.

**Comment by aaronlehmann** [comment]
I've opened https://github.com/docker/docker-ce/pull/67 for docker/swarmkit#2237.

@cyli could you please cherry-pick those two fixes, then I'll update https://github.com/docker/docker-ce/pull/67 ?

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/pull/33472 was merged, so should be ready for cherry-picking if we want it

**Comment by unclejack** [comment]
Is there something I could do to make sure moby/moby#33472 gets cherry-picked for the release?

**Comment by aaronlehmann** [comment]
I know RC3 is already out, but I don't know where else to track this (I agree with @thaJeztah that having a separate issue for each RC is a little tough).

I opened https://github.com/docker/docker-ce/pull/75 for https://github.com/docker/swarmkit/pull/2244.

**Comment by andrewhsu** [comment]
I've moved the backlog to a new issue for tracking 17.06.0 RC4: #14

@aaronlehmann @thaJeztah having a new issue for each RC helps me in managing a smaller list of PRs. Plus, the ticket that is referenced by the tracking issue says the RC release it is tracked in. Willing to discuss a better procedure or use of a better tool to track issues across different repos for the 17.07 release.
